### ISSUE TITLE
Newer version on stackage

### ISSUE THREAD

**Issue by flip111** [scrive/pool#26]
Could a later version of this package be added to stackage ?

Latest LTS https://github.com/commercialhaskell/stackage-snapshots/blob/master/lts/20/11.yaml#L8723-L8726 has `0.2.3.2` at the moment

**Comment by arybczak** [comment]
Please see https://github.com/commercialhaskell/stackage/issues/6852 that tracks this.

**Comment by flip111** [comment]
Ok sorry for posting
