### ISSUE TITLE
What happened to try{With,Take}Resource?

### ISSUE THREAD

**Issue by BardurArantsson** [scrive/pool#7]
Hi,

First off, glad to see that somebody's taken over maintainership.

I'm curious about what happened to try{With,Take}Resource in 0.3.0.0. Is it hard to support or was it just an oversight?

(I only ask before I put a lot of work into CPP and such to get my packages compiling across both 0.2.x and 0.3.x.)

Regards,

**Comment by BardurArantsson** [comment]
Excellent. Thank you :)

**Comment by arybczak** [comment]
Released 0.3.1.0 with the changes.
